experiment_title: write here the purpose of your experiment
dataset:
  script_path: ../data_processing/A_COMPLETER.py # A_COMPLETER
model:
  script_path: ../models/A_COMPLETER.py # A_COMPLETER
optimizer:
  script_path: ../optimizers/adam_keras.py
  initial_lr: 0.0001 # A_COMPLETER
train:
  script_path: ../train/A_COMPLETER.py # A_COMPLETER
  batch_size: 64
  epochs: 1000
  data_augmentation: # POUR EXEMPLE, A MODIFIER
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.1
    height_shift_range: 0.1
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False
evaluate: # POUR EXEMPLE, A MODIFIER
  batch_size: 1000
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False